/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CuerpoRouteImport } from './routes/cuerpo'
import { Route as DiaRouteImport } from './routes/dia'
import { Route as HistorialRouteImport } from './routes/historial'
import { Route as ProgresoRouteImport } from './routes/progreso'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CuerpoRoute = CuerpoRouteImport.update({
  id: '/cuerpo',
  path: '/cuerpo',
  getParentRoute: () => rootRouteImport,
} as any)
const DiaRoute = DiaRouteImport.update({
  id: '/dia',
  path: '/dia',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorialRoute = HistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgresoRoute = ProgresoRouteImport.update({
  id: '/progreso',
  path: '/progreso',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cuerpo': typeof CuerpoRoute
  '/dia': typeof DiaRoute
  '/historial': typeof HistorialRoute
  '/progreso': typeof ProgresoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cuerpo': typeof CuerpoRoute
  '/dia': typeof DiaRoute
  '/historial': typeof HistorialRoute
  '/progreso': typeof ProgresoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cuerpo': typeof CuerpoRoute
  '/dia': typeof DiaRoute
  '/historial': typeof HistorialRoute
  '/progreso': typeof ProgresoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cuerpo' | '/dia' | '/historial' | '/progreso'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cuerpo' | '/dia' | '/historial' | '/progreso'
  id: '__root__' | '/' | '/cuerpo' | '/dia' | '/historial' | '/progreso'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CuerpoRoute: typeof CuerpoRoute
  DiaRoute: typeof DiaRoute
  HistorialRoute: typeof HistorialRoute
  ProgresoRoute: typeof ProgresoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuerpo': {
      id: '/cuerpo'
      path: '/cuerpo'
      fullPath: '/cuerpo'
      preLoaderRoute: typeof CuerpoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dia': {
      id: '/dia'
      path: '/dia'
      fullPath: '/dia'
      preLoaderRoute: typeof DiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historial': {
      id: '/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof HistorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progreso': {
      id: '/progreso'
      path: '/progreso'
      fullPath: '/progreso'
      preLoaderRoute: typeof ProgresoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CuerpoRoute: CuerpoRoute,
  DiaRoute: DiaRoute,
  HistorialRoute: HistorialRoute,
  ProgresoRoute: ProgresoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
